#cloud-config
users:
  - name: itman
    gecos: Ansible User
    groups: users,admin,wheel
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMCGAzqBH2BUWbPtMuyoihDKny7ITaOR/GWye2acwndE kavian.karimzadeh@hotmail.com'
